### ISSUE TITLE
How to listen to websocket connection

### ISSUE THREAD

**Issue by yushu0623** [gidven/saxo-openapi-client-python#1]
Hello,

Thank you very much for creating this really useful package.

I am trying to connect to streaming (websocket) function, but I don't know how..

What I have done so far is as follows:

```
from saxo_apy import SaxoOpenAPIClient

client = SaxoOpenAPIClient(SAXO_APP_CONFIG_DEMO, log_sink="log.txt")

client.login(launch_browser=False, catch_redirect=False,
             redirect_url=client.available_redirect_urls[1], start_async_refresh=False)
```
After making sure successfully logged in, I initiate a websocket connection as below.
```
client.setup_streaming_connection()
```
Then, I am not sure how I can start receiving messages from the server...
(BTW, RestAPI functions are working just fine.)

I would appreciate your help.
Thank you for your great work again.

**Comment by gidven** [comment]
Hi there,

I added a new sample here that covers what you are trying to achieve:
https://github.com/gidven/saxo-openapi-client-python/blob/main/samples/streaming_sample.py

Have fun!

**Comment by yushu0623** [comment]
Works beautifully. Thank you!
