### ISSUE TITLE
Streaming charts as appose to infoprices

### ISSUE THREAD

**Issue by jlsvane** [gidven/saxo-openapi-client-python#4]
Hi.

I've tried to modify file s02_streaming_prices.py to stream 1 minute charts in stead by changing the code to this:

`async def create_subscription() -> None:
    """Create subscription for EURUSD (uic 21) """
    sub = client.post(
        "/trade/v1/charts/subscriptions",
        data ={
                  "Arguments": {
                    "AssetType": "FxSpot",
                    "Count": 3,
                    "FieldGroups": [
                      "ChartInfo",
                      "Data",
                      "DisplayAndFormat"
                    ],
                    "Horizon": 1,
                    "Uic": 21
                  },
                  "ContextId": client.streaming_context_id,
                  "Format": "application/json",
                  "ReferenceId": "my-fx-stream",
                  "RefreshRate": 1000
                  }`

However, this results in errors like this:
...
`  File "/home/novelty/miniconda3/envs/saxo_api/lib/python3.8/site-packages/saxo_apy/client.py", line 322, in post
    response = handle_api_response(self.openapi_request("POST", path, params, data))
  File "/home/novelty/miniconda3/envs/saxo_api/lib/python3.8/site-packages/saxo_apy/utils.py", line 130, in handle_api_response
    raise exc
saxo_apy.models.APIResponseError: status: 404 - NOT FOUND
error: requested resource or entity the request operates on could not be found (or you don't have the required permissions for the requested entity)
`
...

Additionally, how could one create one subscription for streaming multiple candles?

BR

Jorgen

**Comment by gidven** [comment]
Hi Jorgen, see the error message: "requested resource or entity the request operates on could not be found". You are requesting a endpoint that does not exist, the correct one is `/chart/v1/charts/subscriptions`.

As far as the endpoint documentation goes this resource only supports a single instrument per subscription so you'll have to create individual ones for each instrument you want to stream.

**Comment by jlsvane** [comment]
Hi 

Thanks - it works now.

BR

Jorgen
