### ISSUE TITLE
Some issues with pydantic v2 

### ISSUE THREAD

**Issue by J4F8** [gidven/saxo-openapi-client-python#6]
Contratulations @gidven for this work about saxo API

I noticed some issues due to pydantic v2
https://docs.pydantic.dev/2.3/migration/

In the meantime, I installed v1:
pip install pydantic==1.10.12

**Comment by gidven** [comment]
Thanks for raising this. I have pinned the pydantic version in saxo-apy v0.2.8 to the most recent v1 version to prevent breakage. Will be addressed in a later update to migrate over to pydantic v2.
