### ISSUE TITLE
Using Streaming connection in a separate thread?

### ISSUE THREAD

**Issue by reneros** [gidven/saxo-openapi-client-python#8]
Hello gidven,

Thank you so much for this awesome package. It works great!

I'd like to use the streaming connection in a separate thread. Would you have any suggestion how to do this?
The rest-API's are used for trading, I'd like to use the streaming to watch prices and trigger some actions/alerts.

Many thanks,
René

**Comment by reneros** [comment]
Hi Gidven,

I have figured it out; turn out to be very easy :-)

For anyone else with this question.
The websockets don't support Threads, you should go we an asyncio eventloop.

I'm using this code now:


```
 async def start_streaming():
    client.setup_streaming_connection()
    asyncio.create_task(self._receive(), name="ascync_receive")
```

```
    async def _receive(self):
        """ Main event loop that receives all updates from the stream"""
        logger.debug("Starting streaming connection [3]")
        async with SaxoClient.client.streaming_connection as stream:
            async for message in stream:
                decoded = decode_streaming_message(message)
                print(decoded.data)
```

**Comment by gidven** [comment]
Hi there, this would indeed be the correct way to do it as this package depends heavily on `asyncio` for concurrency support. Threads would be possible too but managing those would introduce a lot of extra complexity and overhead when asyncio generally is easier to reason about and just as (if not more) performant for simple tasks like receiving streaming messages :)
